#!/usr/bin/env zsh

from_template() {
	[[ -f "${PROJ}"/"${1}" ]] || cp "${TEMPLATE}"/"${2}" "${PROJ}"/"${1}"
}


BASE=$(cd "$(dirname "${0}")" && pwd)
TEMPLATE=${BASE}/template

[[ -n "${1}" ]] || (( echo "Usage : "${0}" project-name.rb" && exit 1 ))

ARG="${1}"
SPLIT=("${(@s/./)ARG}") 
NOEXT="${SPLIT[1]}"
EXT="${SPLIT[2]}"

PROJ="${BASE}/${1}"

mkdir -p "${PROJ}"
mkdir -p "${PROJ}"/lib
mkdir -p "${PROJ}"/data

cd "${PROJ}"
cucumber --init
cd "${BASE}"

from_template "features/cucumber.feature" "cucumber.feature"

STEPS="${PROJ}"/features/step_definitions/cucumber_steps.rb
[[ -f "${STEPS}" ]] || echo "require_relative \"../../lib/"${ARG}"\"" > "${STEPS}"

from_template "Makefile" "Makefile"

touch "${PROJ}"/lib/"${ARG}"
touch "${PROJ}"/data/"${NOEXT}".in
